# Generated by Django 4.2.6 on 2023-12-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='zadanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('opis', models.CharField(max_length=2000)),
                ('data_postu', models.DateField()),
                ('Stan', models.CharField(choices=[(1, 'wykonane'), (2, 'w trakcie'), (3, 'oczekujące')], max_length=1)),
            ],
        ),
    ]
